# Generated by Django 2.1.1 on 2020-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bang',
            name='posision',
            field=models.CharField(default='', max_length=300),
        ),
    ]
