# Generated by Django 3.0.8 on 2020-08-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usedtrading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('cost', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
