# Generated by Django 3.0.8 on 2020-08-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedtrading',
            name='cost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usedtrading',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image2'),
        ),
        migrations.AlterField(
            model_name='usedtrading',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image3'),
        ),
    ]
